import { useEffect, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import students from './data/students.json'
import seedActivities from './data/activities.json'
import categories from './data/categories.json'

const TARGET_POINTS = 100

function Icon({ name }) {
  const paths = {
    dashboard: <><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></>,
    activity: <><path d="M4 5h16M4 12h16M4 19h16" /><circle cx="7" cy="5" r="1" fill="currentColor" /><circle cx="17" cy="12" r="1" fill="currentColor" /></>,
    plus: <><path d="M12 5v14M5 12h14" /></>,
    categories: <><circle cx="12" cy="12" r="8" /><path d="M12 8v8M8 12h8" /></>,
    profile: <><circle cx="12" cy="8" r="3" /><path d="M5 20c.7-3.3 3.1-5 7-5s6.3 1.7 7 5" /></>,
    logout: <><path d="M10 5H5v14h5M15 8l4 4-4 4M19 12H9" /></>,
    arrow: <><path d="M5 12h13M13 6l6 6-6 6" /></>,
    check: <path d="m5 12 4 4L19 6" />,
    clock: <><circle cx="12" cy="12" r="8" /><path d="M12 7v5l3 2" /></>,
    spark: <><path d="m12 3 1.6 6.4L20 11l-6.4 1.6L12 19l-1.6-6.4L4 11l6.4-1.6L12 3Z" /></>,
    calendar: <><rect x="4" y="5" width="16" height="15" rx="2" /><path d="M8 3v4M16 3v4M4 10h16" /></>,
  }
  return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>
}

function Shell({ student, onLogout, children }) {
  const location = useLocation()
  const pageNames = { '/': 'Overview', '/activities': 'My activities', '/add': 'Add activity', '/categories': 'Categories', '/profile': 'My profile' }
  const currentPage = pageNames[location.pathname] || 'Overview'
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">P</span><span>pointly</span></div>
      <div className="student-mini"><div className="avatar">AM</div><div><strong>{student.name}</strong><small>{student.uid}</small></div></div>
      <nav className="nav-list">
        <span className="nav-label">Workspace</span>
        <NavItem to="/" icon="dashboard" label="Overview" />
        <NavItem to="/activities" icon="activity" label="My activities" />
        <NavItem to="/add" icon="plus" label="Add activity" />
        <span className="nav-label nav-label-lower">Explore</span>
        <NavItem to="/categories" icon="categories" label="Categories" />
        <NavItem to="/profile" icon="profile" label="My profile" />
      </nav>
      <div className="sidebar-bottom"><div className="target-note"><span className="target-dot" /><div><strong>Target progress</strong><small>Keep going, {student.name.split(' ')[0]}!</small></div></div><button className="logout-button" onClick={onLogout}><Icon name="logout" /> Log out</button></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div><span className="eyebrow">Student workspace</span><h1>{currentPage}</h1></div><div className="top-actions"><button className="bell-button" aria-label="Notifications"><span className="bell-dot" />&#128276;</button><div className="top-avatar">AM</div></div></header>
      <div className="content-wrap">{children}</div>
    </main>
  </div>
}

function NavItem({ to, icon, label }) { return <NavLink to={to} end={to === '/'} className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><Icon name={icon} /><span>{label}</span>{label === 'Add activity' && <span className="nav-plus">+</span>}</NavLink> }

function Login({ onLogin }) {
  const [uid, setUid] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const submit = (event) => { event.preventDefault(); const student = students.find((item) => item.uid.toLowerCase() === uid.trim().toLowerCase() && item.password === password); if (student) onLogin(student); else setError('That UID and password combination is not recognised.') }
  return <div className="login-page"><div className="login-visual"><div className="brand brand-light"><span className="brand-mark">P</span><span>pointly</span></div><div className="visual-copy"><span className="pill light-pill">Your progress, in one place</span><h1>Make every<br /><em>experience</em> count.</h1><p>Track the activities that shape your college journey, one point at a time.</p></div><div className="visual-stats"><div><strong>100</strong><span>points to grow</span></div><div><strong>06</strong><span>activity areas</span></div></div></div><div className="login-panel"><div className="login-inner"><span className="eyebrow">Student portal</span><h2>Welcome back.</h2><p className="muted">Sign in to continue your progress.</p><form onSubmit={submit} className="login-form"><label>Student UID<input value={uid} onChange={(event) => setUid(event.target.value)} placeholder="e.g. 22CSE1047" required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" required /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button full-button" type="submit">Sign in <Icon name="arrow" /></button></form><p className="demo-hint">Demo credentials: <strong>22CSE1047</strong> / <strong>student123</strong></p></div><div className="login-footer">Activity points management system <span>2024 / 25</span></div></div></div>
}

function StatCard({ label, value, sub, tone, icon }) { return <div className={`stat-card ${tone}`}><div className="stat-top"><span>{label}</span><span className="stat-icon"><Icon name={icon} /></span></div><strong className="stat-value">{value}</strong><span className="stat-sub">{sub}</span></div> }
function Badge({ status }) { return <span className={`status-badge ${status === 'Approved' ? 'approved' : 'review'}`}><span />{status}</span> }
function ActivityRow({ activity }) { return <div className="activity-row"><div className="activity-main"><div className={`category-marker ${activity.category.toLowerCase().replace(' ', '-')}`} /><div><strong>{activity.title}</strong><span>{activity.category} <i>/</i> {formatDate(activity.date)}</span></div></div><div className="claimed-points"><strong>{activity.claimed}</strong><span>claimed</span></div><div className="approved-points"><strong>{activity.approved || '--'}</strong><span>approved</span></div><Badge status={activity.status} /></div> }
function formatDate(value) { return new Date(`${value}T00:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) }

function Dashboard({ student, activities }) {
  const approved = activities.reduce((total, item) => total + item.approved, 0)
  const claimed = activities.reduce((total, item) => total + item.claimed, 0)
  const remaining = Math.max(TARGET_POINTS - approved, 0)
  return <><section className="welcome-row"><div><span className="eyebrow">Tuesday, December 10, 2024</span><h2>Good morning, {student.name.split(' ')[0]} <span className="wave">&#9786;</span></h2><p className="muted">Here is the latest snapshot of your activity journey.</p></div><NavLink className="primary-button" to="/add"><Icon name="plus" /> Add activity</NavLink></section><section className="stat-grid"><StatCard label="Points earned" value={approved} sub={`of ${TARGET_POINTS} target points`} tone="blue" icon="spark" /><StatCard label="Points remaining" value={remaining} sub="to reach your target" tone="yellow" icon="clock" /><StatCard label="Activities logged" value={activities.length} sub={`${activities.filter((item) => item.status === 'Approved').length} approved activities`} tone="pink" icon="check" /></section><div className="dashboard-grid"><section className="panel activity-panel"><div className="section-heading"><div><span className="eyebrow">Your recent progress</span><h3>Latest activities</h3></div><NavLink to="/activities" className="text-link">View all <Icon name="arrow" /></NavLink></div>{activities.slice(0, 4).map((activity) => <ActivityRow activity={activity} key={activity.id} />)}</section><section className="panel progress-panel"><div className="section-heading"><div><span className="eyebrow">At a glance</span><h3>Target progress</h3></div><span className="progress-percent">{Math.round((approved / TARGET_POINTS) * 100)}%</span></div><div className="ring-wrap"><div className="progress-ring" style={{ '--progress': `${(approved / TARGET_POINTS) * 360}deg` }}><div><strong>{approved}</strong><span>of {TARGET_POINTS} pts</span></div></div></div><p className="progress-message"><strong>{remaining} points</strong> to go. You are building a great record.</p><div className="mini-legend"><span><i className="legend-blue" /> Approved</span><span><i className="legend-gray" /> Remaining</span></div></section></div><section className="insight-banner"><div className="insight-icon"><Icon name="spark" /></div><div><strong>Small steps add up</strong><p>Log your activities while they are fresh. It makes approvals faster and your achievements easier to remember.</p></div><NavLink to="/add" className="banner-link">Log an activity <Icon name="arrow" /></NavLink></section></>
}

function Activities({ activities }) { const [filter, setFilter] = useState('All'); const shown = filter === 'All' ? activities : activities.filter((item) => item.category === filter); return <><section className="page-intro"><div><span className="eyebrow">Activity record</span><h2>Everything you have done.</h2><p className="muted">A clear record of your co-curricular journey.</p></div><NavLink className="primary-button" to="/add"><Icon name="plus" /> Add activity</NavLink></section><div className="filter-bar"><span className="filter-label">Filter by</span>{['All', ...categories.map((item) => item.name)].map((item) => <button className={filter === item ? 'filter-chip selected' : 'filter-chip'} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><section className="panel full-activity-panel"><div className="table-head"><span>Activity</span><span>Claimed</span><span>Approved</span><span>Status</span></div>{shown.map((activity) => <ActivityRow activity={activity} key={activity.id} />)}{!shown.length && <div className="empty-state">No activities found in this category.</div>}</section></> }
function AddActivity({ onAdd }) { const [form, setForm] = useState({ title: '', category: 'Technical', date: '', description: '', claimed: '' }); const [saved, setSaved] = useState(false); const update = (key, value) => setForm((current) => ({ ...current, [key]: value })); const submit = (event) => { event.preventDefault(); onAdd({ ...form, id: Date.now(), claimed: Number(form.claimed), approved: 0, status: 'Under review' }); setSaved(true); setForm({ title: '', category: 'Technical', date: '', description: '', claimed: '' }); }; return <><section className="page-intro"><div><span className="eyebrow">New submission</span><h2>Log an activity.</h2><p className="muted">Tell us about an experience you want to add to your record.</p></div></section><div className="form-layout"><form className="panel activity-form" onSubmit={submit}><div className="form-section-title"><span className="number-badge">01</span><div><h3>Activity details</h3><p>Share the basics about your achievement.</p></div></div><div className="field-grid"><label className="wide-field">Activity title<input value={form.title} onChange={(event) => update('title', event.target.value)} placeholder="e.g. National level hackathon" required /></label><label>Category<select value={form.category} onChange={(event) => update('category', event.target.value)}>{categories.map((item) => <option key={item.id}>{item.name}</option>)}</select></label><label>Date completed<input type="date" value={form.date} onChange={(event) => update('date', event.target.value)} required /></label><label>Points claimed<input type="number" min="1" max="50" value={form.claimed} onChange={(event) => update('claimed', event.target.value)} placeholder="e.g. 10" required /></label><label className="wide-field">Description<textarea value={form.description} onChange={(event) => update('description', event.target.value)} placeholder="What did you do? Add a little context for the reviewer." rows="5" required /></label></div><div className="form-actions"><span className="form-note">Your activity will be marked <strong>Under review</strong>.</span><button className="primary-button" type="submit">Submit activity <Icon name="arrow" /></button></div>{saved && <div className="success-message"><Icon name="check" /> Activity submitted and added to your record.</div>}</form><aside className="form-aside"><div className="aside-illustration"><Icon name="spark" /></div><h3>One more story<br /><em>worth counting.</em></h3><p>Approved activities contribute to your overall target. You can submit any eligible campus or community experience.</p><NavLink to="/categories" className="text-link">Explore categories <Icon name="arrow" /></NavLink></aside></div></> }
function Categories() { return <><section className="page-intro"><div><span className="eyebrow">Where your points come from</span><h2>Find your category.</h2><p className="muted">There are many ways to make an impact at college.</p></div></section><div className="category-grid">{categories.map((category) => <div className={`category-card ${category.color}`} key={category.id}><div className="category-icon">{category.icon}</div><span className="category-count">Eligible activities</span><h3>{category.name}</h3><p>{category.description}</p><NavLink to="/add" className="category-link">Add activity <Icon name="arrow" /></NavLink></div>)}</div></> }
function Profile({ student, activities }) { const approved = activities.reduce((total, item) => total + item.approved, 0); return <><section className="page-intro"><div><span className="eyebrow">Your student identity</span><h2>My profile.</h2><p className="muted">Your information and activity summary.</p></div></section><div className="profile-grid"><section className="panel identity-panel"><div className="profile-hero"><div className="profile-avatar">AM</div><div><h3>{student.name}</h3><p>{student.department}</p><span className="profile-tag">Student since {student.joined}</span></div></div><div className="details-list"><div><span>Student UID</span><strong>{student.uid}</strong></div><div><span>Department</span><strong>{student.department}</strong></div><div><span>Current semester</span><strong>Semester {student.semester}</strong></div><div><span>Email address</span><strong>{student.email}</strong></div></div></section><section className="panel summary-panel"><span className="eyebrow">Point summary</span><h3>Your impact, so far.</h3><div className="profile-total"><strong>{approved}</strong><span>approved points</span></div><div className="summary-bar"><span style={{ width: `${Math.min((approved / TARGET_POINTS) * 100, 100)}%` }} /></div><div className="summary-foot"><span>0 pts</span><strong>{TARGET_POINTS} pts target</strong></div><div className="summary-stats"><div><strong>{activities.length}</strong><span>Activities</span></div><div><strong>{activities.filter((item) => item.status === 'Approved').length}</strong><span>Approved</span></div><div><strong>{activities.filter((item) => item.status === 'Under review').length}</strong><span>In review</span></div></div></section></div></> }

function App() { const [student, setStudent] = useState(() => { const saved = JSON.parse(localStorage.getItem('pointly-student') || 'null'); return saved ? students.find((item) => item.uid === saved.uid) || null : null }); const [activities, setActivities] = useState(seedActivities); useEffect(() => { if (student) localStorage.setItem('pointly-student', JSON.stringify(student)); }, [student]); const login = (value) => setStudent(value); const logout = () => { localStorage.removeItem('pointly-student'); setStudent(null) }; if (!student) return <Login onLogin={login} />; return <Shell student={student} onLogout={logout}><Routes><Route path="/" element={<Dashboard student={student} activities={activities} />} /><Route path="/activities" element={<Activities activities={activities} />} /><Route path="/add" element={<AddActivity onAdd={(activity) => setActivities((current) => [activity, ...current])} />} /><Route path="/categories" element={<Categories />} /><Route path="/profile" element={<Profile student={student} activities={activities} />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Shell> }

export default App
